<nav class="navbar navbar-expand-lg navbar-light bg-white navbar-shadow">
    <div class="navbar-multiline mr-auto">
        <span class="navbar-brand" href="#0">robots.txt Editor</span>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminHome') ?>">Home</a></li>
                <li class="breadcrumb-item"><a href="<?= $this->router->to('adminSetting') ?>">Setting</a></li>
                <li class="breadcrumb-item active" aria-current="page">robots.txt</li>
            </ol>
        </nav>
    </div>
</nav>

<div class="container p-3">
    <div class="row">
        <div class="col-md-12">
            <form method="POST" class="card needs-validation main" novalidate>
                <div class="card-header">
                    robots.txt
                    <div class="float-right">
                        <button class="btn btn-primary">Save</button>
                    </div>
                </div>
                <div class="card-body">
                    <?= $form->csrfField('noob') ?>
                    <?= $form->field('value') ?>
                </div>
            </form>
        </div>
    </div>
</div>

<?php if($success): ?>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            $.toaster({
                content: 'The robots.txt file updated',
                title: 'Success',
                info: 'just now',
                position: 'bottom right'
            })
        });
    </script>
<?php endif; ?>